# Database Configuration - SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=btl_oop_db;trustServerCertificate=true

# T?i kho?n 'sa' v? m?t kh?u b?n ?? t?o
spring.datasource.username=sa
spring.datasource.password=MaiLinh2004@

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=create